name: Server CI

on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        default: false
  pull_request:

concurrency:
  group: server-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/server-setup.yaml

  lint:
    name: Code Quality
    needs: [setup]
    uses: ./.github/workflows/server-lint.yaml

  tests:
    name: Test Suite
    needs: [setup]
    uses: ./.github/workflows/server-tests.yaml

  build:
    name: Build Image
    needs: [lint, tests]
    uses: ./.github/workflows/server-build.yaml

  deploy:
    name: Deploy
    needs: [build]
    if: inputs.deploy == true
    uses: ./.github/workflows/server-deploy.yaml
    secrets: inherit
